# Generated by Django 4.2.1 on 2023-06-15 11:17

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('is_student', models.BooleanField(default=True, null=True)),
                ('loyalty_points', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('department', models.CharField(choices=[('Computing/JMC', 'Computing/JMC'), ('Math', 'Math'), ('Bio-medical engineering', 'Bio-medical engineering'), ('Medicine', 'Medicine')], default='Computing/JMC', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('meal_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=200)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('number_of_reservations', models.IntegerField()),
                ('price_staff', models.DecimalField(decimal_places=2, max_digits=5)),
                ('price_student', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('open_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('order_no', models.BigAutoField(primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('collected', models.BooleanField(default=False)),
                ('qr', models.ImageField(blank=True, upload_to='images/')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.customer')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.meal')),
            ],
        ),
        migrations.AddField(
            model_name='meal',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.restaurant'),
        ),
        migrations.AddField(
            model_name='meal',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
